type Query {
  indicator(id: ID!): Indicator
  indicators: [Indicator]

  entry(id: ID!): Entry
  entries: [Entry]

  impact(entryID: ID!, indicatorID: ID!): Impact
}

type Indicator {
  id: ID!
  method: String!
  category: String!
  indicator: String!
  unit: String!
}

type Entry {
  id: ID!
  productName: String!
  geography: Geography!
  unit: String!
  impact(indicatorID: ID!): Impact!
}

type Impact {
  id: ID!
  indicator: Indicator!
  entry: Entry!
  coefficient: Float!
}

type Geography {
  shortName: String!
  name: String!
}
