"""1st Schema Migration

Revision ID: da1416ac918d
Revises: 
Create Date: 2021-09-01 12:08:02.599417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1416ac918d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geography',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.CHAR(length=36), nullable=True),
    sa.Column('short_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('indicator', sa.VARCHAR(length=100), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=45), nullable=True),
    sa.Column('geography_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['geography_id'], ['geography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impact')
    op.drop_table('entry')
    op.drop_table('indicator')
    op.drop_table('geography')
    # ### end Alembic commands ###
